### ISSUE TITLE
OverlayTrack shows wrong values

### ISSUE THREAD

**Issue by lajoimat** [ivanek/Gviz#1]
The original track values don't show up properly when overlaying tracks

```
# minimal example #

gr1 = GRanges(seqnames = "chr1",ranges = IRanges(start = seq(1,100,by = 10),width = 5))

dt1 <- DataTrack(
  range = gr1,
  data = 1:10,
  alpha.title = 1, 
  alpha = 0.75,
  groups = factor("forward",levels = c("forward", "reverse")),
  type = "hist",
  name = "forward only"
)

dt2 <- DataTrack(
  range = GenomicRanges::shift(gr1,3),
  data = 10:1 + 89,
  alpha.title = 1, 
  alpha = 0.75,
  groups = factor("reverse",levels = c("forward", "reverse")),
  type = "hist",
  name = "reverse only"
)

ot <- OverlayTrack(trackList = list(dt1, dt2),name = "cannot specify name here?")

ot@trackList[[1]]@name = "overlayed\n(wrong reverse values)" # is this the only way to change name?

plotTracks(list(dt1,dt2,ot))

```
![image](https://user-images.githubusercontent.com/7004005/51806316-9a1a9800-2246-11e9-8251-0ea134405ab7.png)

Package: Gviz
Version: 1.20.0

**Comment by ivanek** [comment]
Dear @lajoimat,
Thanks for the report, however, please keep in mind, that `OverlayTracks` class is a very special case. Currently there is no restriction how to setup the overlay (you can combine any track types). Because of that, it is relatively complicated to cover all possible combinations and the user is fully responsible for setting the overlay in a meaningful way. Please see [Gviz User Guide, Chapter 6](http://bioconductor.org/packages/devel/bioc/vignettes/Gviz/inst/doc/Gviz.html#6_track_highlighting_and_overlays). Both, title and axis (if any) are set based on the first track.
