### ISSUE TITLE
plotting 10 or more variables in a custom datatrack bug

### ISSUE THREAD

**Issue by rlinder02** [ivanek/Gviz#37]
Hi all,

Thank you for developing and maintaining this awesome resource!

I encountered a bug that happens once you try to plot 10 or more variables in a single datatrack. The data is plotted in the wrong order- here is a simple example. As seems typical with R, ordering gets funky once you're over 9 (ie 1, 10, 11, ..., 2). I'm using the S. cerevisiae genome as that's what I typically work with.

mycolors <- c("dodgerblue2", "blue2", "skyblue3", "darkturquoise", "brown", "olivedrab", "tomato", "chocolate", "burlywood4", "saddlebrown", "magenta4", "maroon2", "mediumpurple",          "darkcyan", "cornsilk4", "mediumvioletred", "slategray3")
data <- data.frame(matrix(1:51, nrow = 3))
grTest <- GRanges(seqnames = 'chrI', ranges = IRanges(start = c(10, 20, 30), end = c(10, 20, 30)))
mcols(grTest) <- data
grouping <- names(mcols(grTest))
dtrackTest <- DataTrack(range = grTest, genome = "sacCer3", groups = grouping, name = "Test", type = "b", col = mycolors, frame = FALSE, lwd = 3, jitter.x = FALSE, cex = 1, ylim = c(0,55), lty = 1, legend = TRUE)
plotTracks(list(dtrackTest), from = 10, to = 33, cex.axis = 1, cex.title = 1, col.title = "black", col.axis = "black", chromosome = 'chrI').

Thanks for taking a look!

Best,
Rob

**Comment by ivanek** [comment]
Hi Rob,

I believe, this issue is quite general as you pointed out. I would not even call it an issue but rather a feature.
Internally the character vector `groups` is converted to a factor and the levels are sorted alpha-numerically. 
The solution might be to supply the `groups` directly as a factor. Following your example, I assume that the original order of elements `grouping` vector is the desired order. Then you can just add this line before calling `DataTrack` function.

```
grouping <- factor(grouping, levels=grouping)
```

I will also try to preserve the order as an internal part of `Gviz` code.

Hope that proposed solution helps, 
Best
Robert

**Comment by rlinder02** [comment]
Hi Robert- your solution works perfectly- thanks so much!

Best,
Rob
